# Generated by Django 3.1.4 on 2020-12-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feature_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
