# Generated by Django 3.1.4 on 2020-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='IsFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
