# Generated by Django 3.1.4 on 2020-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201216_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
